version: "3"
services:
  api:
    container_name: sparta-note-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
    - 5555:5555
    depends_on:
      - db
    environment:
      PORT: 5555
      GITHUB_USER: galitan-dev
      GITHUB_TOKEN: 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
      PG_HOST: 127.0.0.1
      PG_PORT: 5432
      PG_USER: api
      PG_DB_NAME: sparta-note
      PG_PASSWORD: 8/nrxbYfJM+oo+VhlSvJbYntKr8z/NWZsfYbZbuHKMInzYK62aOnquAIy4TJs4yD6pA2y/TruM6wG+eHMjiKGQ==à
  db:
    container_name: sparta-note-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sparta-note
      POSTGRES_USER: api
      POSTGRES_PASSWORD: 8/nrxbYfJM+oo+VhlSvJbYntKr8z/NWZsfYbZbuHKMInzYK62aOnquAIy4TJs4yD6pA2y/TruM6wG+eHMjiKGQ==à
