version: "3"

x-db-variables: &db-variables
  POSTGRES_HOST: sparta-note-db
  POSTGRES_PORT: 5432
  POSTGRES_USER: api
  POSTGRES_DB_NAME: sparta-note
  POSTGRES_PASSWORD: 8/nrxbYfJM+oo+VhlSvJbYntKr8z/NWZsfYbZbuHKMInzYK62aOnquAIy4TJs4yD6pA2y/TruM6wG+eHMjiKGQ==à

services:
  api:
    container_name: sparta-note-api
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        PORT: 6666
        <<: *db-variables
    ports:
    - 6666:6666
    depends_on:
      - db
  db:
    container_name: sparta-note-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: *db-variables